### ISSUE TITLE
Refactor project as Poetry project

### ISSUE THREAD

**Issue by lynnpepin** [PubInv/project-data#15]
With this issue, this project should be refactored with structure and dependencies as with Poetry: https://python-poetry.org/

The reason for this is that Poetry helps greatly with:

1. Managing dependencies within a project. (Very similar to Rust's 'cargo')
2. Publishing projects to PIP. (Also similar to Rust's 'cargo'.)

I should be taking this on during the next mob-programming.

**Comment by lynnpepin** [comment]
Might be worthwhile to package `okf-library` with Poetry and push to pip too. No more git-submodule reliance!

**Comment by RobertLRead** [comment]
Harry, @lynnpepin created this, and @Jbutler-helpful wanted to get your approval before we merged it---they created the branch called something like "poetry refactoring". Can you review it? We may create a pull request and assign to you as a separate operation.

**Comment by Jbutler-helpful** [comment]
Is this issue closed?

**Comment by devhawk** [comment]
I think this is closed by #20

**Comment by Jbutler-helpful** [comment]
Are all ok if I close this issue?
