### ISSUE TITLE
Add a YAML slurper to read OKHs and OKWs directly

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/project-data#4]
I suspect there is a library in Python that reads in YAML. This would move the project forward.

**Comment by Jbutler-helpful** [comment]
I think we would need take the hardwired OKH and OKW out of the platform

**Comment by Jbutler-helpful** [comment]
should we use subtree vs submoduls (for importing okh and okw from the library)

**Comment by RobertLRead** [comment]
This has been done.  I used a submodule to get all the alphh .yml files from the "library" repo. The bad news is it shows zero consistency, either syntactically or semantically, in the parts of the OKH that we need for them to be machine readable. The following output explains the problem:

`>>> getKnownOKHs()
getKnownOKHs()
Character Generator
None
Character Generator
None
CoVisor Mk II Protective Face Shield
['A. Clear Screen (PET) B. Adjustable Strap (PP/TPS blend)  C. Head Band (PP/TPS blend) D. Screen Support (PP/TPS blend)  E. Head Cover (*supplied with Maxi only - PET)']
CoVisor Mk II Protective Face Shield
['Injection Moulding equipment']
MakerMask: Origami (Beta) – Fitted Mask
['https://makermask.org/materials/']
MakerMask: Origami (Beta) – Fitted Mask
None
Surge Pleated Mask from MakerMask (English)
['Freshly washed spunbond NWPP bags ( 3 sheets', ' 8″ by 9″)', ' Bias tape or other latex-free ties (e.g.', ' cotton ties or silicone ties)', ' Coffee tin ties', ' pipe cleaners or coated paper clips']
Surge Pleated Mask from MakerMask (English)
['Sewing machine', ' Scissors and pins', ' Measuring tape or ruler']
MakerMask: Surge (Oleada) Instrucciones (Español)
[' Bolsas de NWPP spunbond recién lavadas (3 hojas', ' 8 ″ por 9 ″)', ' Cinta al bies u otros lazos sin látex (p. Ej.', ' Lazos de algodón o de silicona)', '   Lazos de lata de café', ' limpiapipas o sujetapapeles recubiertos']
MakerMask: Surge (Oleada) Instrucciones (Español)
['Máquina de Coser', ' Tijeras y alfileres Cinta métrica o regla']
Origami Face Shield
[' Clear PET film Thickness: 5-10 mil Roll stock', ' width: 13”-48”']
Origami Face Shield
None
VentMon v0.4T
['https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/blob/master/design/pcb/ventmon_T0.4/VentMon%20T0.4%20BOM.csv']
VentMon v0.4T
None
[<__main__.OKH object at 0x7fce70745eb0>, <__main__.OKH object at 0x7fce70745520>, <__main__.OKH object at 0x7fce70745bb0>, <__main__.OKH object at 0x7fce70745760>, <__main__.OKH object at 0x7fce70745580>, <__main__.OKH object at 0x7fce70745d90>, <__main__.OKH object at 0x7fce70745310>]`

The Inputs and Required Tooling have no consistency, and the strings are not even delimited properly. Futhermore, we have no notion of the type of the thing we are making, except "title", which is really a name.

This is not too surprising, it just represents a maturation of the OKH that we need to accomplish.

Note: The YML has a lot of information, we are not currently using in the OKH.
