### ISSUE TITLE
Cleanup Maker/Supplier/MakerSupplier types in atoms.py

### ISSUE THREAD

**Issue by devhawk** [PubInv/project-data#41]
In the current python atoms.py code, we separate out different types of OKWs based on tool and supply amounts.

* Maker - has tools, no supplies
* Supplier - has supplies, no tools
* MakerSupplier - has supplies and tools

this distinction at the type system level isn't useful. Should we fold everything into "maker supplier"? If so, what's a better name for that?

**Comment by Jbutler-helpful** [comment]
Let's try having 1 type: Facility 

that can complete action: 
 1. Make
 2. Supply

**Comment by Jbutler-helpful** [comment]
lets try OKWParty

**Comment by devhawk** [comment]
I will investigate Python naming standards to deal with capitalization and word breaking
