### ISSUE TITLE
Importing OKH and OKW from the Library 

### ISSUE THREAD

**Issue by Jbutler-helpful** [PubInv/project-data#43]
We need to be able to import know OKW and OKH directly from libraries 

https://github.com/helpfulengineering/library

**Comment by devhawk** [comment]
since the library is in github, we'll need to use the [git database REST service](https://docs.github.com/en/rest/git) to iterate the OKH/OKW files in the library repo. There doesn't appear to be an [*official* Octokit SDK](https://github.com/octokit) for Python but I found [octokit.py](https://github.com/khornberg/octokit.py) as well as the [official OpenAPI definitions](https://github.com/github/rest-api-description/) for the Github REST services

**Comment by devhawk** [comment]
Blocked on #48

**Comment by 0x2b3bfa0** [comment]
Not anymore 🎉

**Comment by 0x2b3bfa0** [comment]
Alternatively to #48, have you considered either using [GitHub Pages](https://pages.github.com) to serve static files without rate limits, or cloning the repository[^1] and then parsing it locally?

(See also https://github.com/helpfulengineering/project-data-platform/issues/48#issuecomment-1687411893 for a dumb suggestion to bypass rate limits) 🤖 

[^1]: You don't even need Git; see e.g. the REST API for [downloading a repository archive](https://docs.github.com/en/free-pro-team@latest/rest/repos/contents?apiVersion=2022-11-28#download-a-repository-archive-tar).

**Comment by devhawk** [comment]
PATs weren't a reasonable solution (I wasn't going to commit my PAT to the repo and I don't think we want to force anyone who uses the solution to get a PAT).

Downloading the entire repo or using GH Pages are possible workarounds, but now that we have an S3 bucket I'm going to ignore them unless DevOps takes away the S3 bucket. Is that cool @0x2b3bfa0 ?

GH Pages is an interesting idea.

**Comment by 0x2b3bfa0** [comment]
> _Now that we have an S3 bucket I'm going to ignore them unless DevOps takes away the S3 bucket. Is that cool @0x2b3bfa0?_

Awesome! Cool as a [superconducting quantum computer](https://en.wikipedia.org/wiki/Superconducting_quantum_computing). 😄 

> _GitHub Pages is an interesting idea._

Yes, but it doesn't support file listing, and you'd end up having to write a small GitHub Actions workflow to create some sort of index file. 🤦🏼‍♂️ For now, S3 is probably the most convenient solution.

**Comment by devhawk** [comment]
> > _GitHub Pages is an interesting idea._
> 
> Yes, but it doesn't support file listing, and you'd end up having to write a small GitHub Actions workflow to create some sort of index file, which isn't quite convenient. 🤦🏼‍♂️

yeah, I realized that myself after I posted my response
