### ISSUE TITLE
S3 bucket for OKH/W

### ISSUE THREAD

**Issue by devhawk** [PubInv/project-data#48]
GitHub has a limit of 1000 API calls per hour for unauthenticated connections. We often hit this limit during debugging. If we move the library to S3 (or its equivalent) then we won't hit these limits.

**Comment by devhawk** [comment]
I'm still waiting on DevOps to give me a bucket

**Comment by devhawk** [comment]
Since we are still waiting on an S3 bucket, I created an Azure blob storage as a work around.

**Comment by 0x2b3bfa0** [comment]
Sorry for the belated resolution. 🙈

**Comment by 0x2b3bfa0** [comment]
> _GitHub has a limit of 1000 API calls per hour for unauthenticated connections. We often hit this limit during debugging._

Have you considered using a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) to lift this restriction during debugging? 🤖

**Comment by devhawk** [comment]
> > _GitHub has a limit of 1000 API calls per hour for unauthenticated connections. We often hit this limit during debugging._
> 
> Have you considered using a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) to lift this restriction during debugging? 🤖

Yes, but I didn't want to commit a PAT to the repo

**Comment by 0x2b3bfa0** [comment]
Discussion moved to https://github.com/helpfulengineering/project-data-platform/issues/43
