### ISSUE TITLE
need inventory supply tree type

### ISSUE THREAD

**Issue by Jbutler-helpful** [PubInv/project-data#54]
- generate supply trees didn't show the difference between Inventory Items and supply 
    - need inventory supply tree type
    - Supply trees don’t make visual distinction between “inventory” items and “supply” items

**Comment by Jbutler-helpful** [comment]
@devhawk when you have a moment can you attach the most resent output .json file here so @timr11 can finding it when he gets time to work on this

**Comment by devhawk** [comment]
I added it to the PR: https://github.com/helpfulengineering/project-data-platform/pull/57#issuecomment-1707357989

**Comment by Jbutler-helpful** [comment]
@timr11 can you run a test with this code doing a visualization to see how it displays inventory vs suppled items.
